//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIOSeries.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDatabaseSQLite {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDatabaseSQLite() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIOSeries.UI.Properties.ResourceDatabaseSQLite", typeof(ResourceDatabaseSQLite).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CREATE TABLE &quot;genders&quot; (&quot;gender_id&quot; INTEGER NOT NULL,&quot;gender_name&quot; TEXT NOT NULL UNIQUE,&quot;gender_deleted&quot; INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(&quot;gender_id&quot; AUTOINCREMENT));.
        /// </summary>
        internal static string CreateDatabaseGenders {
            get {
                return ResourceManager.GetString("CreateDatabaseGenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CREATE TABLE &quot;series&quot; (
        ///	&quot;serie_id&quot;	INTEGER NOT NULL,
        ///	&quot;gender_id&quot;	INTEGER NOT NULL,
        ///	&quot;serie_name&quot;	TEXT NOT NULL,
        ///	&quot;serie_description&quot;	TEXT,
        ///	&quot;serie_year&quot;	INTEGER,
        ///	&quot;serie_deleted&quot;	INTEGER DEFAULT 0,
        ///	&quot;serie_image&quot;	TEXT,
        ///	FOREIGN KEY(&quot;gender_id&quot;) REFERENCES &quot;genders&quot;(&quot;gender_id&quot;),
        ///	PRIMARY KEY(&quot;serie_id&quot; AUTOINCREMENT)
        ///);.
        /// </summary>
        internal static string CreteDatabaseSeries {
            get {
                return ResourceManager.GetString("CreteDatabaseSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] database_series {
            get {
                object obj = ResourceManager.GetObject("database_series", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
